version: "3"
services:
  develop:
    build: .
    ports:
      - "5702:5702"
    container_name: glad-analysis
    env_file:
      - dev.env
    environment:
      PORT: 5702
      DEBUG: "True"
    command: develop
    volumes:
      - ./gladAnalysis:/opt/gladAnalysis/gladAnalysis
    restart: always
