version: "3"
services:
  test:
    build: .
    ports:
      - "5702"
    container_name: glad-analysis-test
    environment:
      DEBUG: "True"
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: "True"
      AWS_CLOUD_WATCH_LOGGING_ENABLED: "True"
      GATEWAY_URL: http://mymachine:9000
    command: test
