version: "3"
services:
  develop:
    build: .
    ports:
      - "5702:5702"
    container_name: glad-analysis
    env_file:
      - dev.env
    environment:
      PORT: 5702
      DEBUG: "True"
      AWS_REGION: "us-east-1"
      REQUIRE_API_KEY: "True"
      AWS_CLOUD_WATCH_LOGGING_ENABLED: "False"
    command: develop
    volumes:
      - ./gladAnalysis:/opt/gladAnalysis/gladAnalysis
    restart: always
