apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: glad-analysis-athena
  name: glad-analysis-athena
  namespace: gfw
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      name: glad-analysis-athena
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: glad-analysis-athena
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - apps
      containers:
        - args:
            - start
          env:
            - name: PORT
              value: "5702"
            - name: ENVIRONMENT
              value: prod
            - name: GATEWAY_URL
              valueFrom:
                secretKeyRef:
                  key: GATEWAY_URL
                  name: mssecrets
            - name: MICROSERVICE_TOKEN
              valueFrom:
                secretKeyRef:
                  key: MICROSERVICE_TOKEN
                  name: mssecrets
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  key: AWS_REGION
                  name: mssecrets
            - name: REQUIRE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: REQUIRE_API_KEY
                  name: mssecrets
          image: gfwdockerhub/glad-analysis-athena
          imagePullPolicy: Always
          name: glad-analysis-athena
          ports:
            - containerPort: 5702
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 512M
            requests:
              cpu: 250m
              memory: 256M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
